language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g npm
  - npm install -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
 - npm run test-once
after_script:
  - cat ./coverage/PhantomJS*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
env:
  global:
    - secure: l2yu9OC2JlPFrT69948hx/GtCI8vMwK+Nk9HogizDMfvq3xeUaDcqgpTBOdGpfH4vsCkdkjCmNSFKZ1Ukvl8GJE3gmW1Ga3ngk++JplmvFwrTSoO1WvjQMIE6O9AkMTPe2AXrV+Cb/zm4/h4cc9I0a6Vu9xktpaB0sj35PPSmdE=
    - secure: M0qQ2PAuVQr4lld+ZRM3KMsALJU2jYGH9ZzD0Nxljmhz5ZRZnlJAqqKfktA13RUZGfZxUwTQjC4kIpnKjBM2D7TXOX5MTPaayLl35AScZdtjZC15MkY3iwL4TRrkFQVVmAMatXKaojxrOhCfVZdb6aDrGB2kEb9hFu2GTKD452o=
